# Generated by Django 6.0.4 on 2026-05-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='meal',
            new_name='condition',
        ),
    ]
